// Generated by CoffeeScript 1.8.0
(function() {
  window.onload = function() {
    cc.game.onStart = function() {
      return cc.LoaderScene.preload(["HelloWorld.png"], function() {
        var MyScene;
        MyScene = cc.Scene.extend({
          onEnter: function() {
            var action, animation, animationframe, frame, i, size, sprite, _i;
            this._super();
            size = cc.director.getWinSize();
            animationframe = [];
            for (i = _i = 0; _i <= 30; i = ++_i) {
              frame = new cc.SpriteFrame("note.png", cc.rect(128 * i, 0, 128, 128));
              animationframe.push(frame);
            }
            animation = new cc.Animation(animationframe, 0.05);
            action = new cc.RepeatForever(new cc.animate(animation));
            sprite = new cc.Sprite("note.png", cc.rect(0, 0, 128, 128));
            sprite.runAction(action);
            sprite.setPosition(size.width / 2, size.height / 2);
            return this.addChild(sprite);
          }
        });
        return cc.director.runScene(new MyScene());
      }, this);
    };
    return cc.game.run("gameCanvas");
  };

}).call(this);
